name: 'Get Supported maintenance versions'

outputs:
  versions:
    value: ${{ steps.get-maintenance-versions.outputs.versions }}

runs:
  using: composite
  steps:
    - shell: bash
      id: get-maintenance-versions
      run: echo "versions=['5.4', '5.5']" >> ${GITHUB_OUTPUT}
