name: Create Issue in Jira when to-jira label added

on:
  issues:
    types: labeled

jobs:
  createClientJiraIssue:
    if: "${{ github.event.label.name == 'Action: Create Client Jira' }}"
    runs-on: ubuntu-latest
    steps:
      - name: Create jira issue
        uses: hazelcast/github-jira-tool-action@v5
        with:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          TARGET_JIRA_PROJECT: API
          JIRA_LABEL: Java
          ISSUE_TYPE: Bug
  createGuardiansJiraIssue:
    if: "${{ github.event.label.name == 'Action: Create HZG Jira' }}"
    runs-on: ubuntu-latest
    steps:
      - name: Create HZG Jira Test Failure issue
        uses: hazelcast/github-jira-tool-action@v6
        with:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          TARGET_JIRA_PROJECT: HZG
          ISSUE_TYPE: Test Failure
          JIRA_LABEL: from-gh
          # Custom fields must be provided with their IDs, which can be found using the following:
          # https://confluence.atlassian.com/jirakb/find-my-custom-field-id-number-in-jira-744522503.html
          CUSTOM_FIELDS: '"customfield_10496": {"id": "10739"}, "customfield_10498": {"id": "10749"}'
